apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: quickstart
  annotations:
    fluentbit.io/exclude: "true"
spec:
  version: 8.12.2
  count: 1
  elasticsearchRef:
    name: quickstart
